#CARICAMENTO MODULI
from math import sin,cos,asin,pi                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
import json                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
import time                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
import pymongo as mongo                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
from kafka import KafkaConsumer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

#CREAZIONE DATABASE MONGO
client = mongo.MongoClient()                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
db = client.Twinterest                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

#CREAZIONE CONSUMER
con1 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con2 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con3 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con4 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con5 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con6 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con7 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con8 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con9 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con10 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
con11 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
con12 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
con13 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
con14 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
con15 = KafkaConsumer(bootstrap_servers='sandbox.hortonworks.com:6667',auto_offset_reset='earliest',consumer_timeout_ms=1000)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

#ISCRIZIONE CONSUMER AI TOPIC
con1.subscribe(['spagna_en0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
con2.subscribe(['spagna_it0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
con3.subscribe(['spagna_es0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
con4.subscribe(['germania_en0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
con5.subscribe(['germania_it0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con6.subscribe(['germania_es0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
con7.subscribe(['ing_en0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
con8.subscribe(['ing_it0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
con9.subscribe(['ing_es0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
con10.subscribe(['italia_en0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
con11.subscribe(['italia_it0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
con12.subscribe(['italia_es0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
con13.subscribe(['francia_en0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
con14.subscribe(['francia_it0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
con15.subscribe(['francia_es0'])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

#CREAZIONE COLLEZIONI DEI TWEET
spagnaen = db.spagnaen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
spagnait = db.spagnait                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
spagnaes = db.spagnaes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
germaniaen = db.germaniaen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
germaniait = db.germaniait
germaniaes = db.germaniaes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
ingen = db.ingen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
ingit = db.ingit                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
inges = db.inges                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
franciaen = db.franciaen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
franciait = db.franciait                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
franciaes = db.franciaes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
italiaen = db.italiaen                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
italiait = db.italiait                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
italiaes = db.italiaes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

#IMPORTAZIONE POI 
from CSV_TO_DICT import germany_list, italy_list, gb_list, france_list, spain_list                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
print("STEP I") #PRINT DI SURVIVAL

#LONGITUDINI E LATITUDINI DEI POI - UTILI PER SNELLIRE IL LOOP FINALE 
lon_ger=[d['Longitude'] for d in germany_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
lat_ger=[d['Latitude'] for d in germany_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
lon_gb=[d['Longitude'] for d in gb_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
lat_gb=[d['Latitude'] for d in gb_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
lon_fra=[d['Longitude'] for d in france_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
lat_fra=[d['Latitude'] for d in france_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
lon_ita=[d['Longitude'] for d in italy_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
lat_ita=[d['Latitude'] for d in italy_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
lon_spa=[d['Longitude'] for d in spain_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
lat_spa=[d['Latitude'] for d in spain_list]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

#LISTA DELLE FRASI DIVISE PER LINGUA E COLLEZIONE
frase_ger_en= ['Take a break: just ', ' km from you is located the ' ,'. You only need ',' minutes walk.', ' hours drive.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
frase_ger_it= ['Prenditi una pausa: a soli ' , ' km da te si trova ','. Ti bastano ',' minuti a piedi.', ' ore in macchina.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
frase_ger_sp= ['Toma un descanso: a solo ' , ' km de ti se encuentra el ','. Solo necesitas caminar ', ' minutos.',' horas de manejo.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
frase_gb_en= ['Take a break: just ', ' km from you is located the ' ,'. You only need ',' minutes walk.', ' hours drive.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
frase_gb_it= ['Prenditi una pausa: a soli ' , ' km da te si trova ','. Ti bastano ',' minuti a piedi.', ' ore in macchina.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
frase_gb_sp= ['Toma un descanso: a solo ' , ' km de ti se encuentra el ','. Solo necesitas caminar ', ' minutos.',' horas de manejo.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
frase_ita_en= ['Take a break: just ', ' km from you is located the ' ,'. You only need ',' minutes walk.', ' hours drive.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
frase_ita_it= ['Prenditi una pausa: a soli ' , ' km da te si trova ','. Ti bastano ',' minuti a piedi.', ' ore in macchina.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
frase_ita_sp= ['Toma un descanso: a solo ' , ' km de ti se encuentra el ','. Solo necesitas caminar ', ' minutos.',' horas de manejo.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
frase_fra_en= ['Take a break: just ', ' km from you is located the ' ,'. You only need ',' minutes walk.', ' hours drive.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
frase_fra_it= ['Prenditi una pausa: a soli ' , ' km da te si trova ','. Ti bastano ',' minuti a piedi.', ' ore in macchina.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
frase_fra_sp= ['Toma un descanso: a solo ' , ' km de ti se encuentra el ','. Solo necesitas caminar ', ' minutos.',' horas de manejo.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
frase_spa_en= ['Take a break: just ', ' km from you is located the ' ,'. You only need ',' minutes walk.', ' hours drive.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
frase_spa_it= ['Prenditi una pausa: a soli ' , ' km da te si trova ','. Ti bastano ',' minuti a piedi.', ' ore in macchina.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
frase_spa_sp= ['Toma un descanso: a solo ' , ' km de ti se encuentra el ','. Solo necesitas caminar ', ' minutos.',' horas de manejo.']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          

#META-TUPLA CHE PERMETTE L'ITERAZIONE DEL CICLO WHILE + FOR FINALE
cons_coll=[(con1,spagnaen,lon_spa,lat_spa,len(spain_list),spain_list,frase_spa_en),
			(con2,spagnait,lon_spa,lat_spa,len(spain_list),spain_list,frase_spa_it),
			(con3,spagnaes,lon_spa,lat_spa,len(spain_list),spain_list,frase_spa_sp),
			(con4,germaniaen,lon_ger,lat_ger,len(germany_list),germany_list,frase_ger_en),
			(con5,germaniait,lon_ger,lat_ger,len(germany_list),germany_list,frase_ger_it),
			(con6,germaniaes,lon_ger,lat_ger,len(germany_list),germany_list,frase_ger_sp),
			(con7,ingen,lon_gb,lat_gb,len(gb_list),gb_list,frase_gb_en),
			(con8,ingit,lon_gb,lat_gb,len(gb_list),gb_list,frase_gb_it),
			(con9,inges,lon_gb,lat_gb,len(gb_list),gb_list,frase_gb_sp),
			(con10,italiaen,lon_ita,lat_ita,len(italy_list),italy_list,frase_ita_en),
			(con11,italiait,lon_ita,lat_ita,len(italy_list),italy_list,frase_ita_it),
			(con12,italiaes,lon_ita,lat_ita,len(italy_list),italy_list,frase_ita_sp),
			(con13,franciaen,lon_fra,lat_fra,len(france_list),france_list,frase_fra_en),
			(con14,franciait,lon_fra,lat_fra,len(france_list),france_list,frase_fra_it),
			(con15,franciaes,lon_fra,lat_fra,len(france_list),france_list,frase_fra_sp)]                                                                                                                                                                                                                

#CREAZIONE COLLEZIONI POI
germany_POI = db.germany_POI #creazione collezione                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
germany_POI.insert_many(germany_list) #insert document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    

italy_POI = db.italy_POI #creazione collezione                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
italy_POI.insert_many(italy_list) #insert document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

spain_POI = db.spain_POI #creazione collezione                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
spain_POI.insert_many(spain_list) #insert document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        

france_POI = db.france_POI #creazione collezione                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
france_POI.insert_many(france_list) #insert document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      

great_britain_POI = db.great_britain_POI #creazione collezione                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
great_britain_POI.insert_many(gb_list) #insert document                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
print('STEP II') #PRINT DI SURVIVAL                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

#FUNZIONE DISTANZA + RETWEET + AGGIORNAMENTO DATI IN MONGO
while(True):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	for message in cons_coll:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		num_mon = list(range(message[4]))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		for i in message[0]:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			tweet = json.loads(i.value.decode('utf-8'))                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
			long=tweet['coords'][0]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
			lat=tweet['coords'][1]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
			dist_piccole=[(sin(pi/180*1/2*(long - (message[2][n]))))**2 * cos(pi/180*lat)*cos( pi/180*message[3][n])+(sin(pi/180*1/2*(lat -message[3][n])))**2 for n in num_mon]                                                                                                                                                                                                                                                                                                                                                                                                                                   
			distanza=round(2*asin((min(dist_piccole))**(1/2))*6370,3)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
			#toReply = tweet['username']                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
			if distanza < 2:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
				temp=message[6][0]+str(distanza)+message[6][1]+message[5][dist_piccole.index(min(dist_piccole))]['Place']+message[6][2]+str(round(distanza/0.09,1))+message[6][3]                                                                                                                                                                                                                                                                                                                                                                                                                              
				#api.update_status('@' + toReply + " " + temp ) #lo spazio da modificare                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				print(temp,'\n','AUTORE:',tweet['autore'],'\t','ORA:',tweet['ora'],'\t','COORD:',tweet['coords'], '\n')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
				#print(temp,tweet['author'],tweet['ora'],tweet['coords'],'\n')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
			else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
				temp=message[6][0]+str(distanza)+message[6][1]+message[5][dist_piccole.index(min(dist_piccole))]['Place']+message[6][2]+str(round(distanza/100,2))+message[6][4]                                                                                                                                                                                                                                                                                                                                                                                                                               
				#api.update_status('@' + toReply + " " + temp ) #lo spazio da modificare                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				print(temp, '\n', 'AUTORE:', tweet['autore'], '\t', 'ORA:', tweet['ora'], '\t', 'COORD:', tweet['coords'], '\n')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			tweet.update({'distanza in km': distanza,
							'punto_interesse': message[5][dist_piccole.index(min(dist_piccole))]['Place'],
							'coords_PI': [message[5][dist_piccole.index(min(dist_piccole))]['Longitude'], message[5][dist_piccole.index(min(dist_piccole))]['Latitude']],
							'categoria_PI': message[5][dist_piccole.index(min(dist_piccole))]['Category']})                                                                                                                                                                                                                                                                                                                                             
			message[1].insert_one(tweet)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
	time.sleep(5)