#CARICAMENTO MODULI
import time
import tweepy                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
from tweepy import OAuthHandler                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
from tweepy.streaming import StreamListener                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
from tweepy import Stream                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
import kafka                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
import json                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
import re                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
from kafka import KafkaProducer                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                

#DEFINIZIONE CHIAVI TWEEPY
consumer_key="Z7p8MglDaCLLCLnpFlraPnHqD"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
consumer_secret="EEYz0jFriQllpgcKp9mpleao1z9m40nnIh1ahkVJWVezE07AI9"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
access_token="728180608686493696-8bu5jeCSu1DxzJ6YByU07hkG90mQIkc"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
access_token_secret="gcBWnnNMVu91JB1OCDxX5BuaawsrSV3L6aPb5e7CqfSpV"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

auth = OAuthHandler(consumer_key, consumer_secret)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
auth.set_access_token(access_token, access_token_secret)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
api = tweepy.API(auth)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

#CLASS LISTENER PER STREAMING DEI DATI
producer = KafkaProducer(bootstrap_servers='sandbox.hortonworks.com:6667')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
class Listener(tweepy.StreamListener):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
	def on_status(self, status):                                                	                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
		if status.coordinates is not None :                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
			tweet = {'autore': status.user.name,
					'username': status.user.screen_name,
					'ora': status.created_at.strftime("%Y-%m-%d %H:%M:%S"),
					'coords': status.coordinates['coordinates'],
					'descrizione_utente': status.user.description,
					'testo': status.text,
					'lingua': status.lang,
					'account_verificato': status.user.verified}                                                                                                                                                                                                                                                                                                                               
			data_to_kafka = json.dumps(tweet).encode('utf-8')                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
			if ((status.coordinates["coordinates"][1] > 36.3717344344) and (status.coordinates["coordinates"][1] < 42.9081372405) and
				(status.coordinates["coordinates"][0] > -5.7234908299) and (status.coordinates["coordinates"][0] < 2.8985666079)):
				print("spagna")                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				if status.lang == "en":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
					producer.send("spagna_en0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
				elif status.lang == "it":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
					producer.send("spagna_it0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
				else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
					producer.send("spagna_es0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			elif ((status.coordinates["coordinates"][1] > 43.2160061897) and (status.coordinates["coordinates"][1]< 49.3648656683) and
				(status.coordinates["coordinates"][0] > -0.0419706609) and (status.coordinates["coordinates"][0] < 7.5027863676)):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
				print("francia")
				if status.lang == "en":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
					producer.send("francia_en0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
				elif status.lang == "it":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
					producer.send("francia_it0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
				else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
					producer.send("francia_es0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
			elif ((status.coordinates["coordinates"][1] > 47.2982950435) and (status.coordinates["coordinates"][1] < 54.9039819757) and 
				(status.coordinates["coordinates"][0] > 5.0770049095) and (status.coordinates["coordinates"][0] < 15.0403900146)):                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
				print("germania")
				if status.lang == "en":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
					producer.send("germania_en0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
				elif status.lang == "it":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
					producer.send("germania_it0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
				else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
					producer.send("germania_es0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
			elif ((status.coordinates["coordinates"][1] > 51.5248285647) and (status.coordinates["coordinates"][1] < 57.10256028950981) and 
				(status.coordinates["coordinates"][0]> -9.6710546319) and (status.coordinates["coordinates"][0] < -3.1671644751880876)):                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
				print("inghilterra")
				if status.lang == "en":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
					producer.send("ing_en0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
				elif status.lang == "it":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
					producer.send("ing_it0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
				else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
					producer.send("ing_es0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
			elif ((status.coordinates["coordinates"][1] > 35.5086217) and status.coordinates["coordinates"][1] < 47.0833333 and
				(status.coordinates["coordinates"][0] > 12.1833332) and (status.coordinates["coordinates"][0] < 12.5929200)):                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
				print("italia")
				if status.lang == "en":
					producer.send("italia_en0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
				elif status.lang == "it":                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
					producer.send("italia_it0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
				else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
					producer.send("italia_es0", data_to_kafka)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
			else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
				pass                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
		else:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
			pass

#CICLO PER LO STREAMING CONTINUO 
while True:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
	try:                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               
		stream = Listener                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
		stream = Stream(auth = api.auth, listener=stream())                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
		stream.filter(languages=["en","it","es"] ,locations=[-180,-90,180,90])                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
	except Exception as e:
		print(e)
		print("ERRORE")
		time.sleep(900)                                                                                                                                                                         